- name: nginx server install and run
  hosts: web
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
        become: yes
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
        become: yes   