- name: variables from prompt
  hosts: localhost
  vars_prompt:
    - name: username
      prompt: please enter your name
      private: true
    - name: password
      prompt: please enter your password  
      private: false 
  tasks:
    - name: print information
      ansible.builtin.debug:
       msg: "Hi, uswername: {{username}}, password: {{password}}"