- name: variable preference
  hosts: localhost
  vars:
    wishes: "morning-from-play-variable"
  # vars_files:
  #   - vars.yaml
  # vars_prompt:
  #   - name: wishes
  #     prompt: enter your wishes here  
  tasks:
    - name: check preference
      # vars:
      #  wishes: "morning-from-task-variable"
      ansible.builtin.debug:
        msg: "Hello,Good {{wishes}}"


 # 1st - arguments
 # 2nd - task variables 
 # 3rd - file variables      
 # 4th - prompt
 # 5th - play variables
 # 6th - inventory